-- Crear tabla Usuarios
CREATE TABLE Users (
  UserId INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(50) UNIQUE NOT NULL,
  Password VARCHAR(20) NOT NULL,
  Birthdate DATE NOT NULL,
  TelephonePrefixes VARCHAR(10),
  PhoneNumber VARCHAR(20),
  PictureUrl VARCHAR(255),
  City VARCHAR(50),
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- Crear tabla Curriculums
CREATE TABLE Curriculums (
  CurriculumId INT PRIMARY KEY AUTO_INCREMENT,
  UserId INT NOT NULL,
  Title VARCHAR(50) NOT NULL,
  AboutMe VARCHAR(400) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users(UserId)
);
-- Crear tabla Educations
CREATE TABLE Educations (
  EducationId INT PRIMARY KEY AUTO_INCREMENT,
  CurriculumId INT NOT NULL,
  InstitutionName VARCHAR(50) NOT NULL,
  Degree VARCHAR(50) NOT NULL,
  FieldOfStudy VARCHAR(50),
  StartYear INT(11),
  StartMonth VARCHAR(50),
  EndYear INT(11),
  EndMonth VARCHAR(50),
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ResumeId) REFERENCES Resumes(ResumeId)
);
-- Crear tabla WorkExperiences
CREATE TABLE WorkExperiences (
  WorkExperienceId INT PRIMARY KEY AUTO_INCREMENT,
  CurriculumId INT NOT NULL,
  JobTitle VARCHAR(50) NOT NULL,
  CompanyName VARCHAR(50) NOT NULL,
  Description VARCHAR(200) NOT NULL,
  StartYear INT(11),
  StartMonth VARCHAR(50),
  EndYear INT(11),
  EndMonth VARCHAR(50),
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ResumeId) REFERENCES Resumes(ResumeId)
);
-- Crear tabla Skills
CREATE TABLE Skills (
  SkillId INT PRIMARY KEY AUTO_INCREMENT,
  CurriculumId INT NOT NULL,
  SkillName VARCHAR(50) NOT NULL,
  ProficiencyLevel VARCHAR(50) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ResumeId) REFERENCES Resumes(ResumeId)
);
-- Crear tabla Languages
CREATE TABLE Languages (
  LanguageId INT PRIMARY KEY AUTO_INCREMENT,
  CurriculumId INT NOT NULL,
  LanguageName VARCHAR(50) NOT NULL,
  FluencyLevel VARCHAR(50) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ResumeId) REFERENCES Resumes(ResumeId)
);
-- Crear tabla Aptitudes
CREATE TABLE Aptitudes (
  AptitudeId INT PRIMARY KEY AUTO_INCREMENT,
  CurriculumId INT NOT NULL,
  AptitudeName VARCHAR(50) NOT NULL,
  Description TEXT,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ResumeId) REFERENCES Resumes(ResumeId)
);